# Generated by Django 4.2.3 on 2024-04-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_parking_num_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='tipo',
            field=models.CharField(choices=[('Convencional', 'Convencional'), ('Prioritária', 'Prioritária')], default='Convencional', max_length=20),
        ),
    ]
